# .github/workflows/weekly.yml

name: Weekly Content Pipeline

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Run for a specific date (YYYY-MM-DD)'
        required: false
      no_archive:
        description: 'Skip archiving old content (true/false)'
        required: false
        default: 'false'
  schedule:
    - cron: '0 8 * * 1'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@users.noreply.github.com'

      - name: Run Full Content Pipeline
        env:
          # CORRECTIE: De naam van de secret voor de Google API-sleutel
          # is nu gecorrigeerd naar GOOGLE_API_KEY, zodat deze overeenkomt
          # met de naam van de secret in de GitHub repository.
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GHOST_ADMIN_API_URL: ${{ secrets.GHOST_ADMIN_API_URL }}
          GHOST_ADMIN_API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}
        run: |
          ARGS=""
          if [ "${{ github.event.inputs.date }}" != "" ]; then
            ARGS="$ARGS --date ${{ github.event.inputs.date }}"
          fi
          if [ "${{ github.event.inputs.no_archive }}" == "true" ]; then
            ARGS="$ARGS --no_archive"
          fi
          python3 -m src.run_pipeline $ARGS

      - name: Commit and Push Generated Content
        run: |
          # De 'archive/' map toevoegen aan git diff om te controleren of er bestanden zijn gearchiveerd
          if ! git diff --quiet --exit-code -- content/ raw.json curated.json archive/; then
            echo "Wijzigingen gedetecteerd, bezig met committen en pushen..."
            # De 'archive/' map toevoegen aan git add
            git add -f content/*.md raw.json curated.json archive/
            COMMIT_DATE=$(date -u +"%Y-%m-%d")
            git commit -m "docs: Generate content for ${COMMIT_DATE}"
            git push
          else
            echo "Geen wijzigingen om te committen."
          fi