# .github/workflows/weekly.yml

name: Weekly Content Pipeline

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Run for a specific date (YYYY-MM-DD)'
        required: false
      no_archive:
        description: 'Skip archiving old content (true/false)'
        required: false
        default: 'false'
  schedule:
    - cron: '0 8 * * 1'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@users.noreply.github.com'

      - name: Run Full Content Pipeline
        id: content_generation
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          source venv/bin/activate
          ARGS=""
          if [ "${{ github.event.inputs.date }}" != "" ]; then
            ARGS="$ARGS --date ${{ github.event.inputs.date }}"
          fi
          if [ "${{ github.event.inputs.no_archive }}" == "true" ]; then
            ARGS="$ARGS --no_archive"
          fi
          python3 -m src.run_pipeline $ARGS

      - name: Publish to Ghost
        if: success()
        env:
          GHOST_ADMIN_API_URL: ${{ secrets.GHOST_ADMIN_API_URL }}
          GHOST_ADMIN_API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}
        run: |
          source venv/bin/activate
          echo "Publiceren van gegenereerde content naar Ghost CMS..."
          python3 -m src.publish_ghost

      - name: Commit and Push Generated Content
        if: success()
        run: |
          # Controleer of er überhaupt wijzigingen zijn om te committen
          if ! git diff --quiet --exit-code -- content/ raw.json curated.json social_posts.json archive/; then
            echo "Wijzigingen gedetecteerd, bezig met committen en pushen..."
            # --- CORRECTIE HIERONDER ---
            git add -f content/*.md raw.json curated.json social_posts.json archive/
            COMMIT_DATE=$(date -u +"%Y-%m-%d")
            git commit -m "docs: Generate and publish content for ${COMMIT_DATE}"
            git push
          else
            echo "Geen wijzigingen om te committen."
          fi