# .github/workflows/weekly.yml

name: Weekly Content Generation and Deployment

on:
  schedule:
    - cron: '0 8 * * 5'
  workflow_dispatch:
    inputs:
      force_provider:
        description: 'Force a specific provider (or auto for failover)'
        required: true
        default: 'auto'
        type: choice
        options:
          - auto
          - kimi
          - mistral
          - gemini

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.commit.outputs.changes_detected }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Full Content Pipeline
        env:
          # Geef ALLE mogelijke sleutels door
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          # Geef de gekozen provider door aan het script
          FORCED_PROVIDER: ${{ github.event.inputs.force_provider }}
        run: python3 -m src.run_pipeline

      - name: Commit and push generated content
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ci): add weekly generated content"

  deploy-ghost:
    if: needs.build.outputs.changes_detected == 'true'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Belangrijk: check de main branch uit, waar de commit is gemaakt
          ref: 'refs/heads/main'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Publish to Ghost
        env:
          GHOST_ADMIN_API_URL: ${{ secrets.GHOST_ADMIN_API_URL }}
          GHOST_ADMIN_API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}
        run: python3 src/publish_ghost.py