# .github/workflows/weekly.yml

name: Weekly Content Generation and Deployment

on:
  schedule:
    - cron: '0 8 * * 5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # FIX 1: We stellen de default working directory in voor alle 'run' stappen
    # Dit lost het "dubbele map" probleem van de runner op.
    defaults:
      run:
        working-directory: ./Vegan-BioTech-Report
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: Vegan-BioTech-Report/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate All Content (main branch)
        if: github.ref == 'refs/heads/main'
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          echo "::group::Generating weekly newsletter (main branch)"
          python3 -m src.fetch
          python3 -m src.curate
          python3 -m src.draft
          echo "::endgroup::"
          echo "::group::Selecting long-read topic"
          # FIX 2: Gebruik -m voor consistentie, net als bij de andere scripts
          LONGREAD_TOPIC=$(python3 -m src.select_topic)
          if [ -z "$LONGREAD_TOPIC" ]; then
            echo "::error::Failed to select a topic. Exiting."
            exit 1
          fi
          echo "Selected topic: $LONGREAD_TOPIC"
          echo "::endgroup::"
          echo "::group::Generating long-read article"
          LONGREAD_FILENAME="content/longread_$(date +%Y-%m-%d)_en.md"
          # FIX 3: Het script staat in de src/ map
          python3 src/generate_longread.py "$LONGREAD_TOPIC" -o "$LONGREAD_FILENAME"
          echo "::endgroup::"

      - name: Generate All Content (gemini-api branch)
        if: github.ref == 'refs/heads/gemini-api'
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          echo "::group::Generating weekly newsletter (gemini-api branch)"
          python3 -m src.fetch
          python3 -m src.curate
          python3 -m src.draft
          echo "::endgroup::"
          echo "::group::Selecting long-read topic"
          LONGREAD_TOPIC=$(python3 -m src.select_topic)
          if [ -z "$LONGREAD_TOPIC" ]; then
            echo "::error::Failed to select a topic. Exiting."
            exit 1
          fi
          echo "Selected topic: $LONGREAD_TOPIC"
          echo "::endgroup::"
          echo "::group::Generating long-read article"
          LONGREAD_FILENAME="content/longread_$(date +%Y-%m-%d)_en.md"
          python3 src/generate_longread.py "$LONGREAD_TOPIC" -o "$LONGREAD_FILENAME"
          echo "::endgroup::"

      - name: Upload entire project folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-folder
          path: ./Vegan-BioTech-Report

  deploy-ghost:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ # Werkt vanuit de root van de uitgepakte artifact
    steps:
      - name: Download project folder artifact
        uses: actions/download-artifact@v4
        with:
          name: project-folder
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Publish to Ghost
        env:
          GHOST_ADMIN_API_URL: ${{ secrets.GHOST_ADMIN_API_URL }}
          GHOST_ADMIN_API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}
        run: python3 src/publish_ghost.py