# .github/workflows/weekly.yml

name: Weekly Content Generation and Deployment

on:
  schedule:
    - cron: '0 8 * * 5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # --- FIX: Stel een standaard werkmap in voor alle 'run' commando's in deze job ---
    defaults:
      run:
        working-directory: ./Vegan-BioMaterials-TechReport

    steps:
      # Stap 1: Check de code uit in een specifieke submap om de naam te controleren
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: 'Vegan-BioMaterials-TechReport' # Zorgt voor een consistente mapnaam

      # Stap 2: Zet Python op
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      # Stap 3: Installeer dependencies (draait nu in de juiste map)
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Stap 4: Genereer content (main branch)
      - name: Run script to generate content (Main Branch)
        if: github.ref == 'refs/heads/main'
        env:
          KIMI_API_KEY: ${{ secrets.KIMI_API_KEY }} 
        run: python src/main.py

      # Stap 5: Genereer content (gemini-api branch)
      - name: Run script to generate content (Gemini Branch)
        if: github.ref == 'refs/heads/gemini-api'
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python src/main.py

      # Stap 6: Upload artifact, zorg ervoor dat het pad correct is
      - name: Upload markdown content as artifact
        uses: actions/upload-artifact@v4
        with:
          name: markdown-content
          path: ./Vegan-BioMaterials-TechReport/content/*.md

  deploy-substack:
    needs: build
    runs-on: ubuntu-latest

    # --- FIX: Stel ook hier de werkmap in ---
    defaults:
      run:
        working-directory: ./Vegan-BioMaterials-TechReport

    steps:
      # Stap 1: Check de code opnieuw uit (best practice voor een nieuwe job)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: 'Vegan-BioMaterials-TechReport'

      # Stap 2: Download het artifact naar de juiste content-map
      - name: Download markdown content artifact
        uses: actions/download-artifact@v4
        with:
          name: markdown-content
          path: ./Vegan-BioMaterials-TechReport/content

      # Stap 3: Zet Python op
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      # Stap 4: Installeer dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Stap 5: Voer het publicatie-script uit
      - name: Publish to Substack
        env:
          SUBSTACK_EMAIL: ${{ secrets.SUBSTACK_EMAIL }}
          SUBSTACK_PASSWORD: ${{ secrets.SUBSTACK_PASSWORD }}
          SUBSTACK_PUBLICATION_URL: ${{ secrets.SUBSTACK_PUBLICATION_URL }}
        run: python scripts/publish_substack.py