# .github/workflows/weekly.yml

name: Weekly Content Generation and Deployment

on:
  schedule:
    - cron: '0 8 * * 5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- FIX: 'main' branch step now ALSO provides the GOOGLE_API_KEY ---
      - name: Generate content for 'main' branch
        if: github.ref == 'refs/heads/main'
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          python3 -m src.fetch
          python3 -m src.curate
          python3 -m src.draft

      - name: Generate content for 'gemini-api' branch
        if: github.ref == 'refs/heads/gemini-api'
        env:
          # Deze branch heeft alleen de Google key nodig, wat al correct was
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          python3 -m src.fetch
          python3 -m src.curate
          python3 -m src.draft

      - name: Upload markdown content as artifact
        uses: actions/upload-artifact@v4
        with:
          name: markdown-content
          path: content/

  # JOB 2: Publiceer de .md bestanden naar Ghost
  deploy-ghost:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download markdown content artifact
        uses: actions/download-artifact@v4
        with:
          name: markdown-content
          path: content/

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Publish to Ghost
        env:
          GHOST_ADMIN_API_URL: ${{ secrets.GHOST_ADMIN_API_URL }}
          GHOST_ADMIN_API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}
        run: python3 src/publish_ghost.py