name: Weekly Content Generation and Deployment

on:
  schedule:
    - cron: '0 8 * * 5' # Elke vrijdag om 8 uur UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Gebruik een nieuwere versie

      - name: Set up Python 3.11
        uses: actions/setup-python@v5 # Gebruik een nieuwere versie
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script to generate content
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # Of een andere API key afhankelijk van de branch
        run: python src/main.py

      - name: Upload markdown content as artifact
        uses: actions/upload-artifact@v4 # Gebruik een nieuwere versie
        with:
          name: markdown-content
          path: content/*.md

  deploy-substack:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: pip install -r requirements.txt # Zorgt ervoor dat python-substack wordt geinstalleerd

      - name: Download markdown content artifact
        uses: actions/download-artifact@v4
        with:
          name: markdown-content
          path: content

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Publish to Substack
        env:
          SUBSTACK_EMAIL: ${{ secrets.SUBSTACK_EMAIL }}
          SUBSTACK_PASSWORD: ${{ secrets.SUBSTACK_PASSWORD }}
          SUBSTACK_PUBLICATION_URL: ${{ secrets.SUBSTACK_PUBLICATION_URL }}
        run: python scripts/publish_substack.py