# .github/workflows/weekly.yml

name: Weekly Content Generation and Deployment

on:
  schedule:
    - cron: '0 8 * * 5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Stap 1: Check de code uit. We raken hier niets meer aan.
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- DIAGNOSTISCHE STAP ---
      # Deze stap toont ons de exacte mappenstructuur op de server.
      - name: 1. LIST ALL FILES to find the correct path
        run: ls -R
        shell: bash

      # Stap 2: We proberen het script te draaien.
      # Deze stap zal waarschijnlijk weer falen, maar de output van stap 1
      # zal ons vertellen hoe we dit definitief kunnen fixen.
      - name: 2. Attempt to run Python script
        run: python src/main.py
        # Als de map inderdaad dubbel is, zou het commando moeten zijn:
        # run: python Vegan-BioMaterials-TechReport/src/main.py