name: Weekly Content Generation
on:
schedule:
# Draait elke vrijdag om 10:00 UTC
- cron: '0 10 * * 5'
workflow_dispatch:
# Maakt een handmatige startknop in GitHub Actions mogelijk
jobs:
build-and-run:
runs-on: ubuntu-latest
Generated code
steps:
- name: Checkout repository
  uses: actions/checkout@v4

- name: Set up Python
  uses: actions/setup-python@v5
  with:
    python-version: '3.11'

- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt

- name: Run entire pipeline
  env:
    # AI Provider Keys
    GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
    OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
    
    # Ghost CMS Keys
    GHOST_ADMIN_API_URL: ${{ secrets.GHOST_ADMIN_API_URL }}
    GHOST_PUBLIC_URL: ${{ secrets.GHOST_PUBLIC_URL }}
    GHOST_ADMIN_API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}

    # Social Media Keys
    MASTODON_API_BASE_URL: ${{ secrets.MASTODON_API_BASE_URL }}
    MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
    REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
    REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
    REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
    REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
    REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
  run: |
    python3 -m src.run_pipeline

- name: Publish to Ghost
  env:
    GHOST_ADMIN_API_URL: ${{ secrets.GHOST_ADMIN_API_URL }}
    GHOST_ADMIN_API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}
  run: |
    python3 -m src.publish_ghost
    
- name: Publish to Social Media
  env:
    GHOST_PUBLIC_URL: ${{ secrets.GHOST_PUBLIC_URL }}
    MASTODON_API_BASE_URL: ${{ secrets.MASTODON_API_BASE_URL }}
    MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
    REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
    REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
    REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
    REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
    REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
  run: |
    python3 -m src.run_pipeline --publish-social